CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "hashed_password" varchar(255) NOT NULL,
  "is_active" boolean DEFAULT true,
  "is_verified" boolean DEFAULT false,
  "failed_logins" int DEFAULT 0,
  "lock_until" timestamptz,
  "two_factor_enabled" boolean DEFAULT false,
  "two_factor_secret" varchar(255),
  "fingerprint_template" bytea,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "user_roles" (
  "user_id" bigint,
  "role_id" bigint,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "email_verifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "password_resets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "token" varchar(512) UNIQUE NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "expires_at" timestamptz NOT NULL,
  "revoked" boolean DEFAULT false,
  "replaced_by_token" varchar(512)
);

CREATE TABLE "login_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "ip_address" varchar(45) NOT NULL,
  "timestamp" timestamptz DEFAULT (now()),
  "success" boolean NOT NULL
);

CREATE TABLE "otp_codes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "otp_code" varchar(10) NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (now()),
  "method" varchar(20) NOT NULL
);

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "email_verifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_resets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "login_attempts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "otp_codes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
