"""primary key fix

Revision ID: 49d95b227755
Revises: 87bfff3ec595
Create Date: 2025-07-25 13:23:51.395507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d95b227755'
down_revision: Union[str, None] = '87bfff3ec595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.drop_constraint(op.f('otp_codes_user_id_fkey'), 'otp_codes', type_='foreignkey')
    op.drop_column('otp_codes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('otp_codes_user_id_fkey'), 'otp_codes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_column('otp_codes', 'email')
    # ### end Alembic commands ###
