"""Include all models

Revision ID: 5ab1291a6eb7
Revises: ef01292e0000
Create Date: 2025-06-28 19:44:00.349790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab1291a6eb7'
down_revision: Union[str, None] = 'ef01292e0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'id')
    # ### end Alembic commands ###
