"""Fix user_roles primary key

Revision ID: 6b87c2b55684
Revises: 6a8e86bc4bc1
Create Date: 2025-07-25 11:43:14.225770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b87c2b55684'
down_revision: Union[str, None] = '6a8e86bc4bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
