"""primary key fix

Revision ID: 87bfff3ec595
Revises: 2904aac90254
Create Date: 2025-07-25 12:08:46.219539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bfff3ec595'
down_revision: Union[str, None] = '2904aac90254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
