"""db model change

Revision ID: b9865a5ff1f7
Revises: 
Create Date: 2025-07-26 22:00:34.994846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9865a5ff1f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.drop_constraint(op.f('otp_codes_user_id_fkey'), 'otp_codes', type_='foreignkey')
    op.drop_column('otp_codes', 'user_id')
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False)
    op.add_column('otp_codes', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('otp_codes_user_id_fkey'), 'otp_codes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_column('otp_codes', 'email')
    # ### end Alembic commands ###
